// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered study recommendations based on past performance.
 *
 * - getAdaptiveRecommendations - A function that returns study recommendations.
 * - AdaptiveRecommendationsInput - The input type for the getAdaptiveRecommendations function.
 * - AdaptiveRecommendationsOutput - The return type for the getAdaptiveRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AdaptiveRecommendationsInputSchema = z.object({
  testHistory: z.array(
    z.object({
      subject: z.string().describe('The subject of the test.'),
      chapterScores: z.record(z.string(), z.number()).describe('A map of chapter names to scores for that test.'),
    })
  ).describe('A list of past tests, with scores for each chapter in each subject.'),
});

export type AdaptiveRecommendationsInput = z.infer<typeof AdaptiveRecommendationsInputSchema>;

const AdaptiveRecommendationsOutputSchema = z.object({
  recommendations: z.array(
    z.object({
      subject: z.string().describe('The subject to focus on.'),
      chapter: z.string().describe('The chapter to focus on within the subject.'),
      reason: z.string().describe('The reason why this chapter is recommended.'),
    })
  ).describe('A list of recommended chapters to study, with reasons.'),
});

export type AdaptiveRecommendationsOutput = z.infer<typeof AdaptiveRecommendationsOutputSchema>;

export async function getAdaptiveRecommendations(input: AdaptiveRecommendationsInput): Promise<AdaptiveRecommendationsOutput> {
  return adaptiveRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'adaptiveRecommendationsPrompt',
  input: {schema: AdaptiveRecommendationsInputSchema},
  output: {schema: AdaptiveRecommendationsOutputSchema},
  prompt: `You are an AI study advisor. You take in a student's test history and provide a list of chapters they should focus on to improve their overall test score.

Here is the student's test history:

{{#each testHistory}}
Subject: {{subject}}
{{#each chapterScores}}
  Chapter: {{@key}}, Score: {{this}}
{{/each}}
{{/each}}

Based on this history, recommend specific chapters for the student to focus on, and explain why.

Your recommendations should focus on areas where the student is weak, but also consider the relative importance of each chapter to the overall test score.

Return the recommendations in the following JSON format:

{{json recommendations}}
`,
});

const adaptiveRecommendationsFlow = ai.defineFlow(
  {
    name: 'adaptiveRecommendationsFlow',
    inputSchema: AdaptiveRecommendationsInputSchema,
    outputSchema: AdaptiveRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
