
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered study plan generation and reset functionalities.
 *
 * - generateStudyPlan - A function that returns a personalized study schedule.
 * - StudyPlanInput - The input type for the generateStudyPlan function.
 * - StudyPlanOutput - The return type for the generateStudyPlan function.
 * - resetStudyPlan - A function to reset or clear a study plan.
 * - ResetStudyPlanInput - The input type for the resetStudyPlan function.
 * - ResetStudyPlanOutput - The return type for the resetStudyPlan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { Subjects, allSubjects, syllabus } from '@/lib/syllabus';

// Define an array of subject string literals for Zod enum
const subjectEnumValues = [
  Subjects.BIOLOGY,
  Subjects.CHEMISTRY,
  Subjects.PHYSICS,
  Subjects.ENGLISH,
  Subjects.LOGICAL_REASONING
] as const; // Use 'as const' for literal types

// Define the schema for DailyActivity locally, as it's used by StudyPlanOutputSchema
// This will be defined inline in the output schema for the prompt
const DailyActivitySchemaInternal = z.object({
  date: z.string().describe('Date for the activity (YYYY-MM-DD or descriptive like "Week 1, Day 1").'),
  activityType: z.enum(['Study', 'Test', 'Review', 'Rest']).describe('Type of activity for the day.'),
  subjectFocus: z.enum(subjectEnumValues).optional().describe('Primary subject to focus on. Mandatory for "Test" or "Review" activities. Optional for "Study".'),
  chapterFocus: z.array(z.string()).optional().describe('Specific chapters or topics from the syllabus for the subjectFocus to cover for "Study" or "Test" activities. Must be an array of chapter names.'),
  details: z.string().optional().describe('Additional details or notes for the day\'s plan, especially for "Test" type, specify number of tests/questions.'),
});
export type DailyActivity = z.infer<typeof DailyActivitySchemaInternal>;


// --- Study Plan Generation ---

// Define input/output types for exported functions using z.infer from schemas defined inline below
const StudyPlanInputSchemaForTypes = z.object({
  finalPreparationDate: z.string().date().describe('The target final date for preparation (YYYY-MM-DD).'),
  subjectGoals: z.record(z.enum(subjectEnumValues), z.number().min(0).max(100).optional()).describe('A map of subjects to target percentage scores (e.g., {"Biology": 85, "Physics": 75}).'),
  pastPerformanceSummary: z.record(z.enum(subjectEnumValues), z.number().min(0).max(100).optional()).describe('A summary of past average performance scores per subject (e.g., {"Biology": 60, "Chemistry": 55}). This helps identify weaker areas.'),
  studyHoursPerDay: z.number().min(1).max(16).optional().describe('Optional: Average number of hours the student can commit to studying per day.'),
});
export type StudyPlanInput = z.infer<typeof StudyPlanInputSchemaForTypes>;

const StudyPlanOutputSchemaForTypes = z.object({
  schedule: z.array(DailyActivitySchemaInternal).describe('A detailed study schedule, broken down by day or study blocks.'),
  aiGeneralAdvice: z.string().optional().describe('General advice or motivational message from the AI regarding the study plan.'),
});
export type StudyPlanOutput = z.infer<typeof StudyPlanOutputSchemaForTypes>;


export async function generateStudyPlan(input: StudyPlanInput): Promise<StudyPlanOutput> {
  return studyPlannerFlow(input);
}

const studyPlannerPrompt = ai.definePrompt({
  name: 'studyPlannerPrompt',
  input: {
    schema: z.object({
      finalPreparationDate: z.string().date().describe('The target final date for preparation (YYYY-MM-DD).'),
      subjectGoals: z.record(z.enum(subjectEnumValues), z.number().min(0).max(100).optional()).describe('A map of subjects to target percentage scores (e.g., {"Biology": 85, "Physics": 75}).'),
      pastPerformanceSummary: z.record(z.enum(subjectEnumValues), z.number().min(0).max(100).optional()).describe('A summary of past average performance scores per subject (e.g., {"Biology": 60, "Chemistry": 55}). This helps identify weaker areas.'),
      studyHoursPerDay: z.number().min(1).max(16).optional().describe('Optional: Average number of hours the student can commit to studying per day.'),
      // Fields for Handlebars context, not part of user input for the flow
      allSubjects: z.array(z.string()),
      syllabusData: z.record(z.string(), z.array(z.object({ name: z.string(), topics: z.array(z.string()).optional() }))),
    })
  },
  output: {
    schema: z.object({
      schedule: z.array(
        z.object({
          date: z.string().describe('Date for the activity (YYYY-MM-DD or descriptive like "Week 1, Day 1").'),
          activityType: z.enum(['Study', 'Test', 'Review', 'Rest']).describe('Type of activity for the day.'),
          subjectFocus: z.enum(subjectEnumValues).optional().describe('Primary subject to focus on. Mandatory for "Test" or "Review" activities. Optional for "Study".'),
          chapterFocus: z.array(z.string()).optional().describe('Specific chapters or topics from the syllabus for the subjectFocus to cover for "Study" or "Test" activities. Must be an array of chapter names.'),
          details: z.string().optional().describe('Additional details or notes for the day\'s plan, especially for "Test" type, specify number of tests/questions.'),
        })
      ).describe('A detailed study schedule, broken down by day or study blocks.'),
      aiGeneralAdvice: z.string().optional().describe('General advice or motivational message from the AI regarding the study plan.'),
    })
  },
  prompt: `You are an expert AI Study Planner for students preparing for competitive exams like the MDCAT.
Your task is to generate a personalized study timetable to help the student cover the entire syllabus and achieve their goals by the final preparation date. Assume each chapter in the syllabus is comprehensive and requires dedicated study and practice (e.g., may contain hundreds of potential practice questions).

Student Inputs:
- Final Preparation Date: {{finalPreparationDate}}
- Subject Goals (Target %):
{{#each subjectGoals}}
  - {{@key}}: {{this}}%
{{else}}
  No specific subject goals provided. Aim for general improvement.
{{/each}}
- Past Performance Summary (Average %):
{{#each pastPerformanceSummary}}
  - {{@key}}: {{this}}%
{{else}}
  No past performance data provided. Assume beginner level or equal proficiency.
{{/each}}
{{#if studyHoursPerDay}}
- Available Study Hours Per Day: {{studyHoursPerDay}} hours
{{else}}
- Available Study Hours Per Day: Not specified. Assume a standard balanced load (e.g., 4-6 hours).
{{/if}}

Syllabus Overview:
The syllabus is structured by subject, then by chapters. The chapter names you MUST use are provided below.
{{#each syllabusData}}
Subject: {{@key}}. Chapters: {{#each this}}{{.name}}{{#unless @last}}, {{/unless}}{{/each}}.
{{/each}}

Instructions for Plan Generation:
1.  Calculate the total number of study days available until the \`finalPreparationDate\`.
2.  Create a structured daily schedule. For each entry in the schedule, provide:
    - \`date\`: (Use relative dates like "Week 1, Day 1", "Week 1, Day 2", etc. for clarity in plans longer than a few weeks. For very short plans, "YYYY-MM-DD" is acceptable).
    - \`activityType\`: "Study", "Test", "Review", or "Rest".
    - \`subjectFocus\`: (Mandatory for "Test" or "Review" activities. Optional for "Study". Must be a single subject from the syllabus list provided above, e.g., "Biology").
    - \`chapterFocus\`: (Applicable for "Study" or "Test" activities. An array of specific chapter names FROM THE SYLLABUS for the given \`subjectFocus\`. Ensure the plan covers ALL chapters from the syllabus for the main subjects over the total duration. Example: ["Cell Structure & Function", "Bioenergetics"] for Biology).
    - \`details\`: Additional notes.
        - For \`activityType: "Study"\`: Briefly mention what to do (e.g., "Thoroughly read concepts, make concise notes, and solve 10-15 practice MCQs per chapter.").
        - For \`activityType: "Test"\`: Crucially, provide a specific recommendation for testing on the \`chapterFocus\`. Ensure \`subjectFocus\` is provided. Example formats:
          "Test on chapters: {{#each chapterFocus}}{{.}}{{#unless @last}}, {{/unless}}{{/each}}. Recommended: Attempt 2 tests of 20 questions each."
          "Test on chapters: {{#each chapterFocus}}{{.}}{{#unless @last}}, {{/unless}}{{/each}}. Recommended: One comprehensive test of 40-50 questions."
          "Recommended: Focus on {{subjectFocus}}. Attempt 25 questions from {{#if chapterFocus}}{{#each chapterFocus}}{{.}}{{#unless @last}} & {{/unless}}{{/each}}{{else}}the subject{{/if}}."
          The number of questions should be appropriate for the chapters covered. Assume a typical test segment is 20-30 questions.
3.  Prioritize Weaker Areas: Allocate more time and earlier review/test cycles for subjects/chapters where past performance is low or goals are high.
4.  Comprehensive Coverage: Distribute the study of ALL chapters from the syllabus across the available days, ensuring everything is covered at least once before the final date.
5.  Balanced Schedule: Mix study, tests, reviews, and rest. Don't overload days. Distribute subjects.
6.  Realistic Load: If \`studyHoursPerDay\` is given, tailor daily tasks to fit. If not provided, assume about 4-6 hours of focused study.
7.  AI Advice: Provide a short, encouraging general piece of advice related to consistency and strategy.

Output Format:
Return the plan as a JSON object with "schedule" (an array of daily activities) and "aiGeneralAdvice".
Each schedule item: { "date", "activityType", "subjectFocus" (mandatory for Test/Review), "chapterFocus" (optional array of strings from syllabus), "details" (optional string) }.

Example for a Test activity:
{ "date": "Week 3, Day 2", "activityType": "Test", "subjectFocus": "Physics", "chapterFocus": ["Force & Motion", "Work & Energy"], "details": "Test on chapters: Force & Motion, Work & Energy. Recommended: Attempt 1 test of 30 questions covering both." }
Ensure chapterFocus is always an array of strings (chapter names from syllabus for the subjectFocus), even if it's empty or has one chapter. If no specific chapters for a Test activity, provide an empty array for chapterFocus.

Begin generating the plan now.
`,
});

const studyPlannerFlow = ai.defineFlow(
  {
    name: 'studyPlannerFlow',
    inputSchema: StudyPlanInputSchemaForTypes, // Use the schema for the exported type
    outputSchema: StudyPlanOutputSchemaForTypes, // Use the schema for the exported type
  },
  async (input) => {
    const templateInput = {
      ...input,
      allSubjects: allSubjects, // from import
      syllabusData: syllabus    // from import
    };

    // Cast templateInput to the schema type expected by the prompt
    const typedTemplateInput = templateInput as z.infer<typeof studyPlannerPrompt.inputSchema>;

    const {output} = await studyPlannerPrompt(typedTemplateInput);
    if (!output) {
      throw new Error('AI failed to generate a study plan output.');
    }
    if (!output.schedule) {
        throw new Error('AI generated a plan but it has no schedule.');
    }

    const validatedSchedule = output.schedule.map(item => ({
      date: item.date || 'N/A',
      activityType: item.activityType || 'Study',
      subjectFocus: item.subjectFocus,
      chapterFocus: Array.isArray(item.chapterFocus) ? item.chapterFocus.filter(cf => typeof cf === 'string') : [],
      details: item.details
    }));

    return {
      schedule: validatedSchedule,
      aiGeneralAdvice: output.aiGeneralAdvice,
    };
  }
);

// --- Reset Study Plan Functionality ---

const ResetStudyPlanInputSchemaForTypes = z.object({
  planId: z.string().optional().describe('Optional ID of the plan to reset.'),
  reason: z.string().optional().describe('Optional reason for resetting the plan.'),
});
export type ResetStudyPlanInput = z.infer<typeof ResetStudyPlanInputSchemaForTypes>;

const ResetStudyPlanOutputSchemaForTypes = z.object({
  status: z.string().describe('Status message indicating the result of the reset operation.'),
  details: z.string().optional().describe('Optional details about the reset operation.'),
});
export type ResetStudyPlanOutput = z.infer<typeof ResetStudyPlanOutputSchemaForTypes>;

const resetStudyPlanFlowInternal = ai.defineFlow(
    {
        name: 'resetStudyPlanFlowInternal',
        inputSchema: ResetStudyPlanInputSchemaForTypes,
        outputSchema: ResetStudyPlanOutputSchemaForTypes,
    },
    async (flowInput) => {
        console.log('Attempting to reset study plan with input:', flowInput);
        // In a real application, this would interact with data storage
        // or potentially another AI service to clear/reset a plan.
        return {
            status: 'Study plan reset successfully (mock response).',
            details: flowInput.planId ? `Plan ID ${flowInput.planId} was targeted for reset.` : 'No specific plan ID provided for reset.',
        };
    }
);

export async function resetStudyPlan(input: ResetStudyPlanInput): Promise<ResetStudyPlanOutput> {
  return resetStudyPlanFlowInternal(input);
}
