
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides an AI-powered study plan generator.
 *
 * - generateStudyPlan - A function that returns a personalized study schedule.
 * - StudyPlanInput - The input type for the generateStudyPlan function.
 * - StudyPlanOutput - The return type for the generateStudyPlan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { Subjects, allSubjects, syllabus } from '@/lib/syllabus';

// Define an enum for subjects to be used in Zod schema
const SubjectEnum = z.enum(allSubjects as [string, ...string[]]);


export const StudyPlanInputSchema = z.object({
  finalPreparationDate: z.string().date().describe('The target final date for preparation (YYYY-MM-DD).'),
  subjectGoals: z.record(SubjectEnum, z.number().min(0).max(100).optional()).describe('A map of subjects to target percentage scores (e.g., {"Biology": 85, "Physics": 75}).'),
  pastPerformanceSummary: z.record(SubjectEnum, z.number().min(0).max(100).optional()).describe('A summary of past average performance scores per subject (e.g., {"Biology": 60, "Chemistry": 55}). This helps identify weaker areas.'),
  studyHoursPerDay: z.number().min(1).max(16).optional().describe('Optional: Average number of hours the student can commit to studying per day.'),
});

export type StudyPlanInput = z.infer<typeof StudyPlanInputSchema>;

export const DailyActivitySchema = z.object({
  date: z.string().describe('Date for the activity (YYYY-MM-DD or descriptive like "Week 1, Day 1").'),
  activityType: z.enum(['Study', 'Test', 'Review', 'Rest']).describe('Type of activity for the day.'),
  subjectFocus: SubjectEnum.optional().describe('Primary subject to focus on for "Study" or "Test" activities.'),
  chapterFocus: z.array(z.string()).optional().describe('Specific chapters or topics to cover for "Study" activities.'),
  details: z.string().optional().describe('Additional details or notes for the day\'s plan.'),
});

export type DailyActivity = z.infer<typeof DailyActivitySchema>;

export const StudyPlanOutputSchema = z.object({
  schedule: z.array(DailyActivitySchema).describe('A detailed study schedule, broken down by day or study blocks.'),
  aiGeneralAdvice: z.string().optional().describe('General advice or motivational message from the AI regarding the study plan.'),
});

export type StudyPlanOutput = z.infer<typeof StudyPlanOutputSchema>;

export async function generateStudyPlan(input: StudyPlanInput): Promise<StudyPlanOutput> {
  return studyPlannerFlow(input);
}

const studyPlannerPrompt = ai.definePrompt({
  name: 'studyPlannerPrompt',
  input: {schema: StudyPlanInputSchema},
  output: {schema: StudyPlanOutputSchema},
  prompt: `You are an expert AI Study Planner for students preparing for competitive exams like the MDCAT.
Your task is to generate a personalized study timetable to help the student stay on track and achieve their goals by the final preparation date.

Student Inputs:
- Final Preparation Date: {{finalPreparationDate}}
- Subject Goals (Target %):
{{#each subjectGoals}}
  - {{#if @root.allSubjects.includes(@key)}}{{@key}}{{else}}Unknown Subject: {{@key}}{{/if}}: {{this}}%
{{else}}
  No specific subject goals provided. Aim for general improvement.
{{/each}}
- Past Performance Summary (Average %):
{{#each pastPerformanceSummary}}
  - {{#if @root.allSubjects.includes(@key)}}{{@key}}{{else}}Unknown Subject: {{@key}}{{/if}}: {{this}}%
{{else}}
  No past performance data provided. Assume beginner level or equal proficiency.
{{/each}}
{{#if studyHoursPerDay}}
- Available Study Hours Per Day: {{studyHoursPerDay}} hours
{{else}}
- Available Study Hours Per Day: Not specified. Assume a standard balanced load.
{{/if}}

Syllabus Overview:
{{#each @root.syllabusData}}
Subject: {{@key}}
Chapters: {{#each this}}{{.name}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}


Instructions for Plan Generation:
1.  Calculate the total number of days available until the final preparation date.
2.  Create a structured daily or weekly schedule. For each entry in the schedule, specify the date (can be relative like "Week 1, Day 1" or absolute "YYYY-MM-DD"), activityType ("Study", "Test", "Review", "Rest"), subjectFocus (if applicable), chapterFocus (specific chapters/topics for "Study" type, can be an array), and any brief details.
3.  Prioritize Weaker Areas: Allocate more time and focus to subjects/chapters where the student's past performance is lower than their goals, or generally low if no specific goals are set for that subject.
4.  Goal-Oriented: Ensure the plan aims to help the student achieve their stated subjectGoals.
5.  Comprehensive Coverage: Try to cover all relevant chapters from the syllabus for the main subjects (Biology, Chemistry, Physics, English, Logical Reasoning) before the final date.
6.  Balanced Schedule: Include a mix of focused study sessions, practice tests (e.g., chapter tests, subject tests, full mock tests), and dedicated review days. Also, incorporate short rest days or lighter days.
7.  Realistic Load: If studyHoursPerDay is provided, try to align the daily workload with it. If not, assume a reasonable study load.
8.  AI Advice: Provide a short, encouraging general piece of advice for the student based on their plan.

Output Format:
Return the plan as a JSON object with two keys: "schedule" (an array of daily/weekly activities) and "aiGeneralAdvice" (a string).
Each item in the "schedule" array should be an object with "date", "activityType", "subjectFocus" (optional), "chapterFocus" (optional array of strings), and "details" (optional).

Example for a schedule item:
{ "date": "2024-08-15", "activityType": "Study", "subjectFocus": "Biology", "chapterFocus": ["Cell Structure & Function", "Bioenergetics"], "details": "Review notes and practice 10 MCQs from each chapter." }
{ "date": "2024-08-16", "activityType": "Test", "subjectFocus": "Physics", "details": "Take a full mock test on Physics - Section 1 (Force & Motion, Work & Energy)." }

Begin generating the plan now.
`,
});

const studyPlannerFlow = ai.defineFlow(
  {
    name: 'studyPlannerFlow',
    inputSchema: StudyPlanInputSchema,
    outputSchema: StudyPlanOutputSchema,
  },
  async (input) => {
    // Make allSubjects and syllabusData available to the Handlebars template
    const templateInput = {
      ...input,
      allSubjects: allSubjects, // Pass the actual list of subjects
      syllabusData: syllabus // Pass the syllabus
    };

    const {output} = await studyPlannerPrompt(templateInput);
    if (!output) {
      throw new Error('AI failed to generate a study plan.');
    }
    // Ensure the output structure, especially for optional fields in the schedule
    const validatedSchedule = output.schedule?.map(item => ({
      date: item.date || 'N/A',
      activityType: item.activityType || 'Study',
      subjectFocus: item.subjectFocus,
      chapterFocus: item.chapterFocus || [],
      details: item.details
    })) || [];

    return {
      schedule: validatedSchedule,
      aiGeneralAdvice: output.aiGeneralAdvice,
    };
  }
);

// Helper to ensure allSubjects is correctly typed for use in Zod enum if needed elsewhere,
// but for the template, passing it directly is fine.
const allSubjectsTuple = allSubjects as [string, ...string[]];
export const ZodSubjectEnum = z.enum(allSubjectsTuple);
